GET http://localhost:3000/route
content-type: application/json

{
  "amount": 200,
  "tradeType": 0,
  "currencyAmount": {
    "address": "0xdAC17F958D2ee523a2206206994597C13D831ec7",
    "decimals": 18,
    "symbol": "USDT",
    "name": "Tether USD"
  },
  "currency": {
    "address": "0xBB0E17EF65F82Ab018d8EDd776e8DD940327B28b",
    "decimals": 18,
    "symbol": "AXS",
    "name": "Axie Infinity Shard"
  }
}